export const PERMISSIONS = {
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_MANAGE: 'products.manage',
  CATEGORIES_VIEW: 'categories.view',
  CATEGORIES_MANAGE: 'categories.manage',
  UNITS_VIEW: 'units.view',
  SUPPLIERS_VIEW: 'suppliers.view',
  SUPPLIERS_MANAGE: 'suppliers.manage',
  SALES_CREATE: 'sales.create',
  SALES_RETURN: 'sales.return',
  PURCHASE_CREATE: 'purchase.create',
  PURCHASE_COMPLETE: 'purchase.complete',
  OVERVIEW_VIEW: 'overview.view',
  LOYALTY_CONFIGURE: 'loyalty.configure',
  SETTINGS_MANAGE: 'settings.manage',
  PRODUCTS_IMPORT: 'products.import',
  SALES_CANCEL: 'sales.cancel',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_GROUPS: { label: string; permissions: Permission[] }[] = [
  {
    label: 'Bán hàng',
    permissions: [PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_CANCEL],
  },
  {
    label: 'Trả hàng',
    permissions: [PERMISSIONS.SALES_RETURN],
  },
  {
    label: 'Nhập hàng',
    permissions: [PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_COMPLETE],
  },
  {
    label: 'Danh mục',
    permissions: [PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.PRODUCTS_MANAGE, PERMISSIONS.PRODUCTS_IMPORT, PERMISSIONS.CATEGORIES_VIEW, PERMISSIONS.CATEGORIES_MANAGE, PERMISSIONS.UNITS_VIEW],
  },
  {
    label: 'Dashboard',
    permissions: [PERMISSIONS.OVERVIEW_VIEW, PERMISSIONS.LOYALTY_CONFIGURE],
  },
  {
    label: 'Cài đặt',
    permissions: [PERMISSIONS.SETTINGS_MANAGE, PERMISSIONS.SUPPLIERS_VIEW, PERMISSIONS.SUPPLIERS_MANAGE],
  },
];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  STAFF: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.UNITS_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_RETURN,
  ],
  MANAGER: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.UNITS_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_RETURN,
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.PURCHASE_COMPLETE,
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.LOYALTY_CONFIGURE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.PRODUCTS_IMPORT,
    PERMISSIONS.SALES_CANCEL,
  ],
};
