import { buildPermissionConstants, PERMISSION_REGISTRY } from './permission-registry';

const built = buildPermissionConstants();

export const PERMISSIONS = built.PERMISSIONS as Record<string, string>;
export const PERMISSION_GROUPS = built.PERMISSION_GROUPS;
export const PERMISSION_LABELS = built.PERMISSION_LABELS;

export type Permission = string;

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  STAFF: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.UNITS_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_RETURN,
  ],
  MANAGER: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.UNITS_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_RETURN,
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.PURCHASE_COMPLETE,
    PERMISSIONS.OVERVIEW_VIEW,
    PERMISSIONS.LOYALTY_CONFIGURE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.PRODUCTS_IMPORT,
    PERMISSIONS.SALES_CANCEL,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.USERS_MANAGE,
  ],
};
