export const LANG = {
  storeNameSale: 'KA MART',
  storeNameReceipt: 'KA MART',
  storeAddress: '62 Nguyễn Phong Sắc, Khuê Trung, Cẩm Lệ, ĐN',
  storePhoneNumber: '0783231774',
  cashier: 'Thu ngân',

  cash: 'Tiền mặt',
  bankTransfer: 'Chuyển khoản',
  card: 'Thẻ',
  ewallet: 'Ví',
  paymentMethod: 'Phương thức thanh toán',

  tabSale: 'Hóa đơn',
  tabReturn: 'Trả hàng',
  tabPurchase: 'Nhập hàng',
  modeSale: 'Bán hàng',
  modeReturn: 'Trả hàng',
  modeImport: 'Nhập hàng',
  modeCategory: 'Danh mục',
  modeOverview: 'Tổng quan',
  overviewTitle: 'Tổng quan',
  overviewFromDate: 'Từ ngày',
  overviewToDate: 'Đến ngày',
  overviewRefresh: 'Xem báo cáo',
  overviewEmpty: 'Chưa có phiếu trong khoảng ngày này',
  overviewEmptyDetail: 'Chọn một phiếu bên phải để xem chi tiết',
  overviewTypeSale: 'Bán hàng',
  overviewTypeReturn: 'Trả hàng',
  overviewTypePurchase: 'Nhập hàng',
  overviewHeaderCode: 'Mã phiếu',
  overviewHeaderStatus: 'Trạng thái',
  overviewHeaderParty: 'Đối tượng',
  overviewHeaderTotal: 'Tổng tiền',
  overviewHeaderDiscount: 'Giảm giá',
  overviewHeaderLoyaltyDiscount: 'Giảm điểm',
  overviewHeaderCost: 'Giá vốn',
  overviewHeaderRevenue: 'Doanh thu',
  overviewHeaderTime: 'Thời gian',
  overviewFilterAll: 'Tất cả',
  overviewFilterType: 'Loại phiếu',
  overviewTotalValue: 'Tổng tiền hàng',
  overviewTotalRecords: 'Tổng số phiếu',
  overviewGrossProfit: 'Lợi nhuận',
  overviewTotalDiscount: 'Tổng giảm giá',
  overviewTotalLoyaltyDiscount: 'Tổng giảm điểm',
  overviewTotalCost: 'Tổng giá vốn',
  overviewTotalRevenue: 'Tổng doanh thu',
  errLoadOverview: 'Không tải được tổng quan',
  errPasswordIncorrect: 'Mật khẩu không đúng',

  categoryTitle: 'Danh mục hàng hóa',
  categoryCode: 'Mã danh mục',
  categoryName: 'Tên danh mục',
  categoryDescription: 'Mô tả',
  categoryParent: 'Danh mục cha',
  categoryProducts: 'Sản phẩm',
  categoryActions: 'Hành động',
  addCategory: 'Thêm danh mục',
  editCategory: 'Chỉnh sửa',
  deleteCategory: 'Xóa',
  saveCategory: 'Lưu',
  save: 'Lưu',
  cancel: 'Hủy',
  searchCategories: 'Tìm kiếm danh mục...',
  noCategoriesFound: 'Không tìm thấy danh mục nào',
  confirmDelete: 'Bạn có chắc muốn xóa danh mục này?',
  selectParentCategory: 'Chọn danh mục cha',
  rootCategory: 'Danh mục gốc',
  categoryDescriptionPlaceholder: 'Nhập mô tả danh mục...',
  categoryStatus: 'Trạng thái',
  categoryStatusActive: 'Hoạt động',
  categoryStatusInactive: 'Ngừng',
  categoryNamePlaceholder: 'Nhập tên danh mục',
  errLoadCategories: 'Không tải được danh mục',
  errCategoryNameRequired: 'Vui lòng nhập tên danh mục',
  successCategoryUpdated: 'Đã cập nhật danh mục',
  successCategoryCreated: 'Đã thêm danh mục',
  errCategorySave: 'Lỗi lưu danh mục',
  successCategoryDeleted: 'Đã xóa danh mục',
  errCategoryDelete: 'Không xóa được danh mục',

  placeholderSearch: 'Quét mã vạch hoặc nhập mã hàng, tên hàng',
  productUnitSep: '·',
  stockLabel: 'Tồn',
  select: 'Chọn',
  scannedLabel: 'Đã quét:',
  currencySuffix: 'đ',
  increaseQuantity: 'Tăng số lượng',
  itemOptions: 'Tùy chọn',
  closeTabSymbol: '×',

  searchTypeInvoiceCode: 'Số hóa đơn',
  searchTypeProductCode: 'Mã hàng',
  placeholderInvoiceCode: 'Nhập mã hóa đơn...',
  placeholderProductCode: 'Nhập mã hàng...',
  placeholderFromDate: 'Từ ngày',
  placeholderToDate: 'Đến ngày',
  searchBtn: 'Tìm',
  foundInvoiceNote:
    'Chọn hóa đơn để tải danh sách hàng cần trả, sau đó quét mã vạch ở ô tìm kiếm phía trên',
  searchInvoiceHint: 'Nhập thông tin tìm kiếm hoặc chọn khoảng ngày',

  subtotalReturn: 'Tiền trả hàng',
  subtotalSale: 'Tổng tiền hàng',
  discount: 'Giảm giá',
  grossProfitRateShort: 'LN',
  returnFee: 'Phí trả hàng',
  refund: 'Hoàn tiền',
  customerPay: 'Khách cần trả',
  customerPaid: 'Khách thanh toán',
  change: 'Tiền thừa trả lại',
  totalReturn: 'Tổng trả',
  totalPayment: 'Thanh toán',
  changeAmount: 'Tiền thối',
  customerGiven: 'Khách đưa',

  print: 'IN',
  completeReturn: 'HOÀN TẤT TRẢ HÀNG',
  completePayment: 'THANH TOÁN',
  close: 'Đóng',
  printInvoice: 'In hóa đơn',

  saving: 'Đang lưu',
  synced: 'Đã đồng bộ',
  checkingOut: 'Đang thanh toán',

  orderNote: 'Ghi chú đơn hàng',
  customer: 'Khách hàng',
  placeholderCustomer: 'Nhập số điện thoại hoặc tên khách hàng',
  pointsUnit: 'điểm',
  customerPoints: 'Điểm hiện tại',
  customerName: 'Tên khách hàng',
  customerPhone: 'Số điện thoại',
  addCustomerName: 'Thêm tên',
  editCustomerName: 'Sửa tên',
  customerNameSaved: 'Đã lưu tên khách hàng',
  redeemPoints: 'Đổi điểm',
  transactionEarn: 'Tích điểm',
  transactionRedeem: 'Đổi điểm',
  transactionSaleOut: 'Bán hàng',
  transactionReturnIn: 'Trả hàng',
  transactionReturnReverse: 'Hoàn điểm',
  transactionPurchaseIn: 'Nhập hàng',
  redeemAmount: 'Giảm theo điểm',
  loyaltyDiscount: 'Giảm giá tích điểm',
  earnPointsEstimate: 'Điểm dự kiến cộng',
  customerNew: 'Khách mới',
  pointHistory: 'Lịch sử điểm',
  loyaltyConfig: 'Cấu hình tích điểm',
  saveConfig: 'Lưu cấu hình',
  earnAmountPerPoint: 'Số tiền / 1 điểm',
  redeemAmountPerPoint: 'Giá trị 1 điểm',
  minimumRedeemPoints: 'Điểm tối thiểu để dùng',
  pointsExpiryDays: 'Số ngày hết hạn điểm',
  errLoadCustomer: 'Không tra cứu được khách hàng',
  errCustomerNameRequired: 'Vui lòng nhập tên khách hàng',
  errCustomerPhoneRequired: 'Vui lòng nhập số điện thoại khách hàng',
  errCustomerSave: 'Không lưu được khách hàng',
  errLoadPointHistory: 'Không tải được lịch sử điểm',
  errLoadLoyaltySettings: 'Không tải được cấu hình tích điểm',
  errSaveLoyaltySettings: 'Không lưu được cấu hình tích điểm',
  loyaltySettingsSaved: 'Đã lưu cấu hình tích điểm',

  emptyCart: 'Chưa có sản phẩm trong tab này',
  emptyCartCheckout: 'Giỏ hàng đang trống',

  loadedInvoice: (code: string) => `Đã tải hóa đơn ${code}`,
  returnCreated: (code: string) => `Đã trả hàng - ${code}`,
  saleCreated: (code: string) => `Đã tạo ${code}`,

  errLoadTab: 'Không tải được tab POS',
  errSaveTab: 'Không lưu được tab tạm',
  errCreateTab: 'Không tạo được tab mới',
  errCreateReturnTab: 'Không tạo được tab trả hàng',
  errCreatePurchaseTab: 'Không tạo được tab nhập hàng',
  errCloseTab: 'Không đóng được tab',
  errProductNotFound: 'Không tìm thấy sản phẩm',
  errInvoiceNotFound: 'Không tìm thấy hóa đơn',
  errLoadInvoice: 'Lỗi tra cứu hóa đơn',
  errLoadInvoiceDetail: 'Không tải được chi tiết hóa đơn',
  errReturnFailed: 'Trả hàng thất bại',
  errPaymentFailed: 'Thanh toán thất bại',
  exactChange: 'Tiền thừa',
  errFeatureDev: 'Chức năng đang phát triển',
  errPrintWindow: 'Không mở được cửa sổ in',
  errLoadSuppliers: 'Không tải được danh mục nhà cung cấp',
  errSupplierNameRequired: 'Vui lòng nhập tên nhà cung cấp',
  errSupplierPhoneInvalid: 'Số điện thoại không hợp lệ (VD: 0912345678)',
  errSupplierSave: 'Không lưu được nhà cung cấp',
  errCompletePurchaseDev: 'Chức năng hoàn thành phiếu nhập sẽ nối backend sau',

  warnNeedTab: 'Cần ít nhất một tab POS',
  warnSelectSupplierToEdit: 'Hãy chọn nhà cung cấp để sửa',

  receiptTitle: 'HÓA ĐƠN TẠM TÍNH',
  receiptReturnTitle: 'PHIẾU TRẢ HÀNG',
  receiptPurchaseTitle: 'PHIẾU NHẬP HÀNG',
  receiptCode: 'Số HĐ',
  receiptPurchaseCode: 'Mã phiếu nhập',
  receiptUnitPrice: 'Đơn giá',
  receiptQty: 'SL',
  receiptTotal: 'Thành tiền',
  receiptFooter: 'Cảm ơn và hẹn gặp lại!',
  receiptPoweredBy: 'Powered by KIOTVIET',
  receiptInvoice: 'Hóa đơn',
  receiptDate: 'Ngày',
  receiptProductTotal: 'Tiền hàng',
  receiptSupplier: 'Nhà cung cấp',
  receiptPaidSupplier: 'Tiền trả NCC',
  receiptDebtSupplier: 'Công nợ',

  purchaseHeader: 'Nhập hàng',
  purchaseImportDate: 'Ngày nhập',
  purchaseOrderCode: 'Mã phiếu nhập',
  purchaseSupplierOrderCode: 'Mã đặt hàng nhập',
  purchaseStatus: 'Trạng thái',
  purchaseSupplierInvoiceCode: 'Số hóa đơn đầu vào',
  purchaseSupplier: 'Nhà cung cấp',
  purchaseAddSupplier: 'Thêm nhà cung cấp',
  purchaseEditSupplier: 'Sửa nhà cung cấp',
  purchaseAutoCode: 'Mã phiếu tự động',
  purchaseDraftStatus: 'Phiếu tạm',
  purchasePayable: 'Cần trả nhà cung cấp',
  purchasePaidAmount: 'Tiền trả nhà cung cấp',
  purchaseDebtAmount: 'Tính vào công nợ',
  purchaseSaveDraft: 'Lưu tạm',
  purchaseComplete: 'Hoàn thành',
  purchaseCompleted: 'Hoàn thành phiếu nhập',
  purchaseEmpty: 'Chưa có hàng nhập trong tab này',
  purchaseNoSupplier: 'Chưa chọn nhà cung cấp',
  purchaseSearchSupplier: 'Chọn nhà cung cấp',
  purchaseNoSuppliersFound: 'Không có nhà cung cấp',
  purchaseToolbarLayout: 'Bố cục',
  purchaseToolbarAdd: 'Thêm dòng',
  purchaseToolbarPrint: 'In phiếu',
  purchaseToolbarPreview: 'Xem phiếu',
  purchaseToolbarAlert: 'Cảnh báo',
  addTab: 'Thêm tab',
  closeTab: 'Đóng tab',
  closeTabUnsaved: 'Tab này chưa thanh toán. Bạn muốn?',
  closeTabPay: 'Thanh toán',
  closeTabDiscard: 'Xóa hẳn',
  openTab: 'Mở tab',
  modeSaleTip: 'Mở tab bán hàng',
  modeReturnTip: 'Mở tab trả hàng',
  modeImportTip: 'Mở tab nhập hàng',
  modeCategoryTip: 'Mở danh mục hàng hóa',
  productTitle: 'Danh mục sản phẩm',
  productCode: 'Mã SP',
  productName: 'Tên SP',
  productCost: 'Giá vốn',
  productPrice: 'Giá bán',
  productStock: 'Tồn',
  productUnit: 'ĐVT',
  productBarcode: 'Mã vạch',
  productStatus: 'Trạng thái',
  productActive: 'Hoạt động',
  productInactive: 'Ngừng',
  productActions: 'Hành động',
  addProduct: 'Thêm SP',
  editProduct: 'Sửa',
  deleteProduct: 'Xóa',
  saveProduct: 'Lưu',
  searchProducts: 'Tìm kiếm sản phẩm...',
  noProductsFound: 'Không tìm thấy sản phẩm nào',
  confirmDeleteProduct: 'Bạn có chắc muốn xóa sản phẩm này?',
  errLoadProducts: 'Không tải được danh sách sản phẩm',
  errSaveProduct: 'Lỗi lưu sản phẩm',
  errDeleteProduct: 'Không xóa được sản phẩm',
  successProductCreated: 'Đã thêm sản phẩm',
  successProductUpdated: 'Đã cập nhật sản phẩm',
  successProductDeleted: 'Đã xóa sản phẩm',
  productCodeRequired: 'Vui lòng nhập mã sản phẩm',
  productNameRequired: 'Vui lòng nhập tên sản phẩm',
  scanBarcode: 'Quét mã vạch',
  barcodePlaceholder: 'Quét hoặc nhập mã vạch...',
  modeOverviewTip: 'Mở tổng quan',
  purchaseTableNo: 'STT',
  purchaseTableImportDate: 'Ngày nhập',
  purchaseTableCode: 'Mã hàng',
  purchaseTableName: 'Tên hàng',
  purchaseTableUnit: 'ĐVT',
  purchaseTableStock: 'Số tồn',
  purchaseTableQty: 'Số lượng nhập',
  purchaseTablePrice: 'Đơn giá',
  purchaseTableDiscount: 'Giảm giá',
  purchaseTableTotal: 'Thành tiền',
  supplierName: 'Tên nhà cung cấp',
  supplierCode: 'Mã nhà cung cấp',
  supplierPhone: 'Số điện thoại',
  supplierAddress: 'Địa chỉ',
  supplierNamePlaceholder: 'Nhập tên nhà cung cấp',
  supplierCodePlaceholder: 'Nhập mã nhà cung cấp',
  supplierPhonePlaceholder: 'Nhập số điện thoại',
  supplierAddressPlaceholder: 'Nhập địa chỉ',
  settingsTitle: 'Cấu hình',
  settingsSectionStore: 'CỬA HÀNG',
  settingsSectionReceipt: 'HÓA ĐƠN',
  settingsSectionLoyalty: 'TÍCH ĐIỂM',
  settingsStoreName: 'Tên cửa hàng',
  settingsStoreAddress: 'Địa chỉ',
  settingsStorePhone: 'Số điện thoại',
  settingsStorePhonePlaceholder: 'VD: 0912345678',
  settingsReceiptHeader: 'Header hóa đơn',
  settingsReceiptFooter: 'Footer hóa đơn',
  addSupplier: 'Thêm nhà cung cấp',
  editSupplier: 'Sửa nhà cung cấp',
  saveSupplier: 'Lưu nhà cung cấp',
  successSupplierCreated: 'Đã thêm nhà cung cấp',
  successSupplierUpdated: 'Đã cập nhật nhà cung cấp',

  // Login page
  loginSuccess: 'Đăng nhập thành công',
  loginFailed: 'Đăng nhập thất bại',
  loginMark: 'KA',
  loginTitle: 'KA MART POS',
  loginSubtitle: 'Đăng nhập hệ thống',
  loginUsernameLabel: 'Tài khoản',
  loginUsernameRequired: 'Nhập tài khoản',
  loginPasswordLabel: 'Mật khẩu',
  loginPasswordRequired: 'Nhập mật khẩu',
  loginButton: 'Đăng nhập',

  // Change password
  changePassword: 'Đổi mật khẩu',
  changePasswordTitle: 'Đổi mật khẩu',
  changePasswordOld: 'Mật khẩu cũ',
  changePasswordNew: 'Mật khẩu mới',
  changePasswordConfirm: 'Xác nhận mật khẩu',
  changePasswordRequired: 'Vui lòng nhập mật khẩu',
  changePasswordMismatch: 'Mật khẩu xác nhận không khớp',
  changePasswordSuccess: 'Đã đổi mật khẩu',
  changePasswordSame: 'Mật khẩu mới phải khác mật khẩu cũ',
  errChangePasswordWrong: 'Mật khẩu cũ không đúng',
  errChangePassword: 'Không đổi được mật khẩu',

  // Logout
  logoutTooltip: 'Đăng xuất',
  logoutSuccess: 'Đã đăng xuất',

  // Permission warnings
  permissionDenied: 'Bạn không có quyền thực hiện thao tác này',
  errManagerOnlyImport: 'Chỉ Manager được nhập hàng',
  errManagerOnlyCategory: 'Chỉ Manager được quản lý danh mục',
  errManagerOnlyLoyaltyConfig: 'Chỉ Manager được cấu hình tích điểm',
  errManagerOnlyOverview: 'Chỉ Manager được xem tổng quan',

  // Overview badges
  overviewBadgePurchase: 'NK',
  overviewBadgeReturn: 'TH',
  overviewBadgeSale: 'BH',

  // Settings messages
  settingsLoadError: 'Không thể tải cấu hình',
  settingsSaved: 'Đã lưu',
  settingsSaveError: 'Lỗi lưu cấu hình',
  settingsDays: 'ngày',

  // Product manager
  productTotalCount: 'Tổng số:',
  productImportExcel: 'Import Excel',
  productLoading: 'Đang tải...',
  productCodePlaceholder: 'VD: SP001',
  productNamePlaceholder: 'Nhập tên sản phẩm',
  productUnitPlaceholder: 'Chọn ĐVT',
  productImportTitle: 'Import sản phẩm từ Excel',
  productImportParsing: 'Đang phân tích file Excel...',
  productImportProcessing: 'Đang xử lý...',
  productImportCompleted: (total: number, created: number, updated: number) => `Import hoàn tất: ${total} dòng (tạo ${created}, cập nhật ${updated})`,
  productImportFailed: 'Import thất bại',
  productImportSuccess: 'Import thành công',
  productImportFileName: 'Tên file:',
  productImportTotalRows: 'Tổng số dòng:',
  productImportCreated: 'Thêm mới:',
  productImportUpdated: 'Cập nhật:',
  productImportInProgress: 'Đang import...',
  productImportElapsed: 'Đã chạy:',
  productImportDropHint: 'Nhấp hoặc kéo thả file Excel vào đây',
  productImportFormatHint: 'Chỉ hỗ trợ file .xlsx',

  // Overview detail
  purchaseTableQtyShort: 'Số lượng',

  // Extended settings labels
  settingsSectionPayment: 'THANH TOÁN',
  settingsSectionCode: 'MÃ TỰ ĐỘNG',
  settingsSectionSearch: 'TÌM KIẾM',
  settingsSectionOther: 'KHÁC',
  settingsCurrencySuffix: 'Ký hiệu tiền tệ',
  settingsLocale: 'Ngôn ngữ/định dạng',
  settingsReceiptPaperWidth: 'Khổ giấy in',
  settingsReceiptPoweredBy: 'Chữ cuối hóa đơn',
  settingsDefaultPaymentMethod: 'PTTT mặc định',
  settingsQuickPayAmount1: 'Nút nhanh 1',
  settingsQuickPayAmount2: 'Nút nhanh 2',
  settingsQuickPayAmount3: 'Nút nhanh 3',
  settingsSalesOrderPrefix: 'Tiền tố HĐ bán',
  settingsReturnOrderPrefix: 'Tiền tố HĐ trả',
  settingsPurchaseOrderPrefix: 'Tiền tố phiếu nhập',
  settingsProductSearchMaxResults: 'KQ tìm kiếm SP',
  settingsInvoiceSearchMaxResults: 'KQ tìm HĐ',
  settingsCustomerSearchMaxResults: 'KQ tìm KH',
  settingsDefaultAddQuantity: 'SL mặc định thêm',
  settingsOverviewPassword: 'Mật khẩu tổng quan',
  settingsCashierLabel: 'Nhãn thu ngân',
  settingsProductManagerPageSize: 'Số dòng QL SP',
  settingsSearchDebounceMs: 'Delay tìm kiếm (ms)',
  settingsAutoSaveDebounceMs: 'Delay tự lưu (ms)',
  settingsPaymentMethods: 'PT Thanh toán (dấu phẩy)',

  // Undo
  undoRemoved: 'Đã xóa sản phẩm',
  undoAction: 'Hoàn tác',

  // Session (end-of-day)
  sessionStart: 'Bắt đầu ca',
  sessionEnd: 'Kết thúc ca',
  sessionEndTitle: 'Kết thúc ca làm việc',
  sessionStartConfirm: 'Xác nhận bắt đầu ca?',
  sessionEndConfirm: 'Xác nhận kết thúc ca?',
  sessionStartedAt: 'Bắt đầu lúc',
  sessionEndedAt: 'Kết thúc lúc',
  sessionTotalSales: 'Tổng bán',
  sessionTotalReturns: 'Tổng trả',
  sessionTotalInvoices: 'Số hóa đơn',
  sessionTotalCash: 'Tiền mặt',
  sessionTotalTransfer: 'Chuyển khoản',
  sessionRunning: 'Ca đang hoạt động',
  sessionInactive: 'Chưa bắt đầu ca',
  sessionSummary: 'Tổng kết ca',
} as const;

export type LangKeys = keyof typeof LANG;
